name: build-docs

on: 
  push:
    branches: [ main ]

jobs:
  build_sphinx_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim
    steps:
      - uses: actions/checkout@v2
      - name: Run build script for Sphinx pages
        run: "docs/build.sh"
        shell: bash
